name: Release NixOS unstable ISO
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [update-flake-lock]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare /nix
        shell: bash
        env:
          CLEAN: "true"
          BTRFS: "true"
        run: |
          curl -o prepare.sh https://raw.githubusercontent.com/JohnRTitor/nixpkgs-review-gha/refs/heads/main/helpers/prepare.sh
          bash prepare.sh

      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            accept-flake-config = true
            build-dir = /nix/var
            experimental-features = nix-command flakes
            sandbox = true
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build
        run: |
          env NIXPKGS_ALLOW_BROKEN=1 nix build .#nixosConfigurations.nixos-minimal.config.system.build.isoImage --impure
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Unstable-ISO.iso
          path: result/iso/

  release:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: Unstable-ISO.iso

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous build
          automatic_release_tag: continuous
          prerelease: false
          draft: false
          files: |
            *.iso*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
