name: Release NixOS unstable ISO
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [update-flake-lock]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Check repo
        uses: actions/checkout@v4

      - name: Build Minimal ISO
        run: |
          env NIXPKGS_ALLOW_BROKEN=1 nix build .#nixosConfigurations.nixos-minimal.config.system.build.isoImage --impure

      - name: Upload artifact  
        uses: actions/upload-artifact@v4.4.0
        with:
          name: Unstable-ISO.iso
          path: result/iso/

  release:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: Unstable-ISO.iso

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous build
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          draft: false
          files: |
            *.iso*
          repo_token: ${{ secrets.GITHUB_TOKEN }}
