name: check-flake

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            accept-flake-config = true
      - run: nix flake check